version: 2
jobs:
  build:
    working_directory: ~/react-webpack-skeleton
    docker:
      - image: phryg1an/circleci-node:8.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum ".nvmrc" }}-yarn-lock-{{ checksum "yarn.lock" }}
            - v1-{{ checksum ".nvmrc" }}-npm-package-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          key: v1-{{ checksum ".nvmrc" }}-yarn-lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-{{ checksum ".nvmrc" }}-npm-package-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Checking code style
          command: |
            mkdir -vp /tmp/test-results
            yarn lint -- --format junit --output-file /tmp/test-results/eslint.xml
      - run:
          name: Scanning dependencies for vulnerabilities
          command: |
            yarn run security
      - run:
          name: Testing
          command: |
            mkdir -vp /tmp/test-results
            yarn test --silent -- --reporter xunit > /tmp/test-results/mocha.xml
      - run:
          name: Generating code coverage report
          command: |
            yarn run coverage -- --report-dir coverage
            mkdir -vp /tmp/test-results
            cp coverage/lcov.info /tmp/test-results/coverage.lcov
      - store_artifacts:
          path: coverage
      - run:
          name: Merging test results
          command: |
            mkdir -vp /tmp/test-results/junit
            node_modules/.bin/junit-merge --dir /tmp/test-results --out /tmp/test-results/junit/all.xml
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Generate documentation
          command: |
            yarn run documentation
      - store_artifacts:
          path: docs
      - run:
          name: Building assets for production
          command: |
            NODE_ENV=production yarn build
      - store_artifacts:
          path: index.html
      - store_artifacts:
          path: index.css
      - store_artifacts:
          path: index.js
