version: 2
jobs:
  build:
    working_directory: ~/react-webpack-skeleton
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test
