version: 2
jobs:
  build:
    working_directory: ~/react-webpack-skeleton
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build assets
          command: yarn build
      - run:
          name: Run tests
          command: mkdir -p /tmp/junit && yarn test --silent -- --reporter xunit > /tmp/junit/test-results.xml
      - store_test_results:
          path: /tmp
