version: 2
jobs:
  build:
    working_directory: ~/react-webpack-skeleton
    docker:
      - image: phryg1an/circleci-node:8.1.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum ".nvmrc" }}-yarn-lock-{{ checksum "yarn.lock" }}
            - v1-{{ checksum ".nvmrc" }}-npm-package-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          key: v1-{{ checksum ".nvmrc" }}-yarn-lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-{{ checksum ".nvmrc" }}-npm-package-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Checking code style
          command: |
            mkdir -vp /tmp/test-results/junit
            yarn lint -- --format junit --output-file /tmp/test-results/junit/eslint.xml
      - run:
          name: Scanning dependencies for vulnerabilities
          command: |
            yarn run security
      - run:
          name: Testing
          command: |
            mkdir -vp /tmp/test-results/junit
            yarn test --silent -- --reporter xunit > /tmp/test-results/junit/mocha.xml
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Building assets for production
          command: |
            NODE_ENV=production yarn build
      - store_artifacts:
          path: index.js
