#!/usr/bin/env bash

SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)
BASE_DIR=$(dirname "${SCRIPTS_DIR}")
SOURCE_DIR=${BASE_DIR}/src
NODE_MODULES_DIR=${BASE_DIR}/node_modules

NYC=${NODE_MODULES_DIR}/.bin/nyc

(cd "${BASE_DIR}" && "${NYC}" --temp-directory .nyc $* report) || exit 1
