#!/usr/bin/env bash

SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)
BASE_DIR=$(dirname "${SCRIPTS_DIR}")
SOURCE_DIR=${BASE_DIR}/src

JSDOC=${BASE_DIR}/node_modules/.bin/jsdoc

(cd "${SOURCE_DIR}" && find . -type f -name index.js | xargs "${JSDOC}" --destination "${BASE_DIR}/docs" --readme "${BASE_DIR}/README.md") || exit 1
