#!/usr/bin/env bash

SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)
BASE_DIR=$(dirname "${SCRIPTS_DIR}")
SOURCE_DIR=${BASE_DIR}/src

(
  cd "${SOURCE_DIR}"
  find . -type f -name spec.js | xargs eslint spec.setup.js || exit 1
  find . -type f -name spec.js | xargs mocha $* \
    --compilers js:babel-register \
    --require babel-polyfill \
    spec.setup.js
)
